### ISSUE TITLE
May 2019 Content Update

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [microsoft/MCW-App-modernization#24]
Hello,
This workshop is scheduled for a May 2019 update.  Please review open issue #23 and give your suggested updates for SME review.

**Comment by jstulo** [comment]
Here are my update suggestions:

- Review lab for latest screens, terminology

- Move starter app into repo

- Move Azure Function into APIM and remove the function proxy

**Comment by danielshue** [comment]
Are we purposely having the student go through software install and basic configuration? To save time, can we point the user to an image similar to what I do for my Containers workshop? see https://github.com/danielshue/containersworkshop

**Comment by karlrissland** [comment]
In general, this needs more "Modernization".  This is targeted for developers but there is very little development happening here.  You are basically setting up azure, making some config changes, then deploying from visual studio.

Show developers how to move from a SQL based auth system to Azure AD B2C
Show developers all the advantages of moving to App Service (backup, deployment slots, scale, etc.)
Show developers all the advantages of SQL Azure (backup, geo replication, etc.)
Pull apart a classic asp.net app to use serverless (move a controller to a function for example)
Replace search code so it uses azure search
Convert a Web API to an API App

Discuss business and technical reasons why a certain decision was made, i.e. why functions vs containers, why power apps, why logic app?

Specific Changes
Before the Hands On Lab
- Should be automated: create an arm template and scripts to setup the environment
- Is there a specific reason for SQL Express and SQL management Studio?  Why do Local DB and Visual Studio not fit the bill here?

Update to Visual Studio 2019

Remove the function proxy and put into APIM

Add App Insights

Use the SQL Data Migration Assistant instead of installing and using SQL to move the data.  You can find the tool here; https://www.microsoft.com/en-us/download/details.aspx?id=53595 NOTE: the technology being used is using DACPACs and BACPACs this has been known to have issues with large amounts of data.

Use the new App Migration tool to migrate your app from IaaS to PaaS.

Setup Azure DevOps to deploy your application, right click publish from visual studio is not a best practice for production deployments.

Instead of using the GUI to provision everything, use the Azure CLI.  It will be easier for users to review the steps and easier to maintain long term.  Lastly, this helps promote infrastructure as code.  Alternatively, you could provide an ARM template which would deploy the new PaaS/Serverless environment.

Make the Identity and Security section optional.  Have had several individuals not have global admin permissions.  Would be easier to pair them up with someone who does for this section.

**Comment by jstulo** [comment]
Most of the MCWs still take the learner through setting up a dev box vm. I think there is still some value in taking them through that.

Regarding some of the other suggested updates. I believe the intent of this one was focused on a team who is very comfortable with on-prem and traditional tooling (SQL management studio). The scenario has used a "baby steps" approach. Many of the suggestions are great ideas. While PaaS/Serverless approaches are definitely more modern they are covered in-depth in other MCWs.

Unless my understanding of the audience and goal is wrong, perhaps the right question is does the title of this workshop match the intent - moving an app from on-prem to Azure.

**Comment by waltermyersiii** [comment]
I agree we want to take them through the s/w install and basic config as part of the learning. I would like to point them to your setup as an option, Dan, but we can't assume you will update this continually. So we would have to think about borrowing it from you and incorporating, perhaps next update.

To Karl's points, we can do some but obviously not all. Let's get on a call to discuss.

**Comment by karlrissland** [comment]
@jstulo I don't think there is much value walking someone through a dev workstation setup.  Better value providing a well documented automation template/script so if they are interested, they can dive in and understand how to replicate it themselves but, they still get a dev environment up and running in 15 to 20min.

As for the content, at this point, the workshop is more of a migration workshop as opposed to modernization.  That is cool if that is the intent, but if the intent is to help people modernize what they are doing then it needs to better define what it means to "Modernize" and show them how to get there.  Just lifting and shifting to PaaS isn't modernization in and of itself.  Getting to PaaS/Serverless/containers is where you need to get so you can start modernizing.

**Comment by DawnmarieDesJardins** [comment]
@karlrissland @waltermyersiii 
Thanks Karl, 
I sent out a meeting request for tomorrow afternoon so we can better discuss the feedback. Looking forward to talking to you then.

**Comment by kylebunting** [comment]
@DawnmarieDesJardins, I have updated the outline for doing a rewrite of this workshop. Please have the team review it at https://github.com/solliancenet/MCW-App-modernization-v2.

**Comment by waltermyersiii** [comment]
Looks good, Kyle. I do think we should add an ARM template as an option for the Before HOL.

**Comment by ManuInNZ** [comment]
As an enduser, "customer" of the MCWs I really would love to see all the
MCWs with simple "Before HOL" e.g. simple ARM templates or Azure DevOps
YAML pipelines.

Cheers
Manu

Le mar. 7 mai 2019 à 12:57, Walter Myers III <notifications@github.com> a
écrit :

**Comment by waltermyersiii** [comment]
Hi Manu,

I agree we should. It will take some time but we can get there as we move through our quarterly update cycles.

Walter

**Comment by waltermyersiii** [comment]
Let's make the move from Windows Form to ASP.NET Core. Focus on the modernization process to .NET Core and the advantages of going this route vs. ASP.NET.

**Comment by waltermyersiii** [comment]
Oops, Windows Forms. :-)

**Comment by rajanbhayana** [comment]
Can we also add in a use case for logic apps and azure functions please? most of websites have these scheduled jobs running for ad hoc tasks and may be we can showcase how azure functions and logic apps can be leveraged. Also since we are taking about ASP.NET Core, may be showcase web app linux hosting to deploy web UI.

**Comment by rajanbhayana** [comment]
Also can we update the documentation to showcase how application insights can be used for all the components (web, functions,logicapps). Also showcase AAD with Azure DevOps as tht is a frequent ask. If we can add service bus here (like web UI notifications) then this workshop basically covers the entire azure integration offering too.
