### ISSUE TITLE
HTTP error 502.5 - Process Failure

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [microsoft/MCW-App-modernization#42]
We have a Partner who is currently conducting App Moderniztion Workshop https://github.com/Microsoft/MCW-App-Modernization and it has been noticed that there are issues which are reported  we are currently unable to get through this issue.

https://github.com/microsoft/MCW-App-modernization/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20App%20modernization.md#task-5-deploy-the-api-to-azure

Exercise4: Task 5: Step 8

Could you please check on this issue and have this fixed or let us know a workaround on this issue?

 
![HTTP error](https://user-images.githubusercontent.com/39317565/70349068-de88a400-1818-11ea-90db-7ad926433f18.jpg)

**Comment by kylebunting** [comment]
I am not able to reproduce this issue. I used the ARM template in the Before the hands-on lab guide to set up a new environment, and I’ve run through the lab without any issues. Could you please verify for me that you are using the latest guide from GitHub and have followed all of the configuration steps correctly? The errors you are seeing would indicate to me that the API App is not able to correctly connect to Key Vault. Could you verify Key Vault was configured properly and that the service principal was given the proper “GET” and “LIST” access policies to Key Vault?

Also, please verify you configured the API app correctly to connect to Key Vault. The steps for this are in Exercise 4, Task 3.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as no response to this or email attempts for more information.

**Comment by brharr** [comment]
Could you please re-open this as I am having the exact same problem and I have been trying to teach this Live on my Streaming channel. I have tried a number of different times and I have tried deploying it to both the Web and API services with the same Process Starting Failure. I even looked at the log files and they gave me little to no information about what was causing the error. 

I ran the ARM template in the Pre-HOL Guide and then performed each step from the API deployment task and received a slightly different error: 

HTTP Error 500.30 - ANCM In-Process Start Failure

Thanks,
Brian

Dawnmarie - I promise to respond to emails if you would like me to help out with this.

**Comment by DawnmarieDesJardins** [comment]
Reopening issue, thanks Brian
@kylebunting @timahenning

**Comment by codingbandit** [comment]
@brharr I was able to reproduce your issue. A couple of things that I did to fix the issue. 

When running locally on the VM, make sure you login to Visual Studio using the same credentials you used when logging into the Azure Portal.

Even though .NET Core 2.2 looks like it's installed from Visual Studio (in the project drop down) - it really isn't - do the steps to install .NET Core 2.2. (Exercise 4, Task 8-10) - I just went directly to the website to do the install on the VM.

Another thing I did was I copied and pasted the SQL Server Connection string forgetting to swap out the password token (Exercise 3, Task 2, steps 2 and 3)

I also did this on-stream, so codingbandit is the channel - the approximate timestamp of recreating the issue is around the 1:45 mark (the video is marked with the name of the MCW) for reference.

**Comment by brharr** [comment]
@codingbandit So I just tried what you suggested and that did not fix the problem. One thing to keep in mind is that I am not using the LabVM, because I shouldn't have to. I have all the software that I need to do this installed on my local machine. 

In addition, the LabVM process is not what a lot of customers would be using in true Development environment and was certainly not what I recommended when I was a Microsoft CSA.

I also checked my SQL connection string that is stored within the KeyVault and I did verify that I had made sure to update the user and password information before storing it. 

Any other ideas because I have tried it multiple times from different machines into different App Service instances with no luck.

**Comment by walterhmyersiii** [comment]
Brian, it has long been our policy that we test in a Lab VM with specified settings and that our expectation is that those who use the workshops will use the same. It is the only way we can ensure that we can solve problems and not have the "well it works on my machine" problem, which is present here.

**Comment by timahenning** [comment]
@brharr Brian, could you test the solution using the Lab VM?

**Comment by kylebunting** [comment]
I will be doing a test-fix for this workshop by the end of next week, so I'll see if I can reproduce the issue this time around. It is outside of the normal process, but I already have all the tools installed on my local machine, so I can quickly check things from there as well.

@brharr, please note that, as @walterhmyersiii stated, the policy is for us to only support the lab setup using the "official" direction in the lab guides. We use the Lab VM because there are too many local machine setups possible for us to effectively support possible issues.

**Comment by brharr** [comment]
@kylebunting I did as you asked and went through the steps using the LabVM and that did work just fine as I am sure you expected. I understand your and Walters stance, but that does not work well in an education environment. You cannot guarantee that a customer's environment will match yours and they are trying to learn from what you are providing in your Hands-On Lab. So as an educator and teacher of this content, I will humbly and emphatically disagree and say so to all of my students. That is bad practice.

To try and help understand the problem, I made sure to pay attention to every single step and screenshot and I found that there are some differences. For example, the data migration now performs with a warning and that is not expected. The Vulnerability Assessment numbers are dramatically different from the screenshot and I believe that the VS2019 version on the LabVM is definitely different from mine. I have the latest version and the LabVM does not. So I am guessing that that might be causing the problems or it could be something else entirely.

**Comment by kylebunting** [comment]
@brharr, I am actively going through the lab and fixing any discrepancies that have resulted from recent updates in Azure, including the "Warning" with the migration you mentioned. I will be done with my fixes today, and they should be available within a few days, depending on when @DawnmarieDesJardins is able to review and approve the changes.

I also noticed some changes to the Framework settings used in the API and Web Apps, so that could also play a role in resolving some of the issues. Those are reflected in my updates.

In addition, I have run this from my workstation without any issues, so this, in my opinion, comes down to some environment different, perhaps with versions of .NET Core installed or other configuration with VS 2019. I fully appreciate your perspective and understand how it can make things more difficult if you are working within a customer's environment. However, we also have to work within defined budgets to provide support for these workshops. Trying to account for every variable that could be different on a user's individual workstation could make it nearly impossible to effectively do that. Not to mention, that would make it very difficult or impossible at times to troubleshoot issues, since we would have no way of replicating the environment in which the errors are happening.

One thing I think you could try is to change the deployment settings for the API app in Visual Studio, as follows: 

1. On the Publish page in Visual Studio, select the pencil (Edit) icon next to Deployment Mode: Framework-Dependent.
2. In the dialog that appears, change the deployment mode to Self-Contained.
3. Select Save.
4. Re-publish the site and attempt to navigate to the /swagger page.

![image](https://user-images.githubusercontent.com/5960229/74783173-21ccad80-5273-11ea-8115-d94bf5c73bc3.png)

**Comment by kylebunting** [comment]
@brharr, my pull request has been submitted with the latest updates (#47). Once @DawnmarieDesJardins has had a chance to go through her review and QC process, that will be merged into master and available.

**Comment by DawnmarieDesJardins** [comment]
Closing as complete with merge of PR #47
