### ISSUE TITLE
Trial subscriptions

### ISSUE THREAD

**Issue by s-leonard** [microsoft/MCW-App-modernization#46]
Hi

I'm going to be running this workshop in March. I've seen the hands on lab section says: 

```
Microsoft Azure subscription must be pay-as-you-go or MSDN.
Trial subscriptions will not work.
```

I was planning on getting Azure Passes for the attendees. I'm not too sure if they fall under trial subscriptions or have the same limitations. Do you know what part of the lab wont work in trial subscriptions, so that I can test that part first with an Azure Pass.

**Comment by kylebunting** [comment]
@s-leonard, I reviewed all of the services used in this workshop, and I think everything will work without issue using Azure Passes, assuming they have sufficient credit to cover the cost of all resources running for 4-5 hours. It would probably be a good idea, however, to run through the lab using one of the passes to verify, so you don't run into issues on the day you run the workshop with customers.

The one area where I'm not sure what will happen is the exercise dealing with Power Apps. I believe you can do a free trial there, but haven't ever tried to run the lab with a non-paid subscription. 

I'll leave this issue open for now, so you can perform some testing. Please keep me updated if you run into issues. Otherwise, feel free to close this issue.

**Comment by s-leonard** [comment]
Okay thanks, I have a spare pass I can test this with next week, so I will do that and let you know.

**Comment by DawnmarieDesJardins** [comment]
@s-leonard 
Hi Steve!  Checking in with you to see if you'd had a chance to test this out.  May we close this open issue?  Dawnmarie

**Comment by DawnmarieDesJardins** [comment]
Closing issue as no further communication from field.  We can reopen as needed if issue still persists.
